In [1]:
""" numpy is wriiten in c which are compiled an super fast.This is the main reason Numpy is up to 50x faster than python list"""

' numpy is wriiten in c which are compiled an super fast.This is the main reason Numpy is up to 50x faster than python list'

In [2]:
""" NumPy Arrays
Same data type only, Much faster(c-level),High memory efficiency,vector operation -Easy -> fast
"""

' NumPy Arrays\nSame data type only, Much faster(c-level),High memory efficiency,vector operation -Easy -> fast\n'

In [4]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [8]:
#suppose we are making list with different data type
a=[1,2,3,4,'amit']
a

[1, 2, 3, 4, 'amit']

In [10]:
np.array(a) #this convert all number into string value 

array(['1', '2', '3', '4', 'amit'], dtype='<U21')

In [11]:
a=[1,2,3,4,4.5]
a

[1, 2, 3, 4, 4.5]

In [12]:
np.array(a)#now all value are converted into float

array([1. , 2. , 3. , 4. , 4.5])

In [13]:
#list doesnot support multidimensiona
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
#then we use array in numpy for supporting multidimension 
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#generating Array
arr= np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr= np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
#we can also generate zeroes
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
#if we want to generate matrix 
arr= np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr= np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
#linspacea:- return evenly number over a specified interval
arr=np.linspace(1,5,2)#(start,end,number present in between)
arr

array([1., 5.])

In [21]:
arr=np.linspace(1,5,88)
arr

array([1.        , 1.04597701, 1.09195402, 1.13793103, 1.18390805,
       1.22988506, 1.27586207, 1.32183908, 1.36781609, 1.4137931 ,
       1.45977011, 1.50574713, 1.55172414, 1.59770115, 1.64367816,
       1.68965517, 1.73563218, 1.7816092 , 1.82758621, 1.87356322,
       1.91954023, 1.96551724, 2.01149425, 2.05747126, 2.10344828,
       2.14942529, 2.1954023 , 2.24137931, 2.28735632, 2.33333333,
       2.37931034, 2.42528736, 2.47126437, 2.51724138, 2.56321839,
       2.6091954 , 2.65517241, 2.70114943, 2.74712644, 2.79310345,
       2.83908046, 2.88505747, 2.93103448, 2.97701149, 3.02298851,
       3.06896552, 3.11494253, 3.16091954, 3.20689655, 3.25287356,
       3.29885057, 3.34482759, 3.3908046 , 3.43678161, 3.48275862,
       3.52873563, 3.57471264, 3.62068966, 3.66666667, 3.71264368,
       3.75862069, 3.8045977 , 3.85057471, 3.89655172, 3.94252874,
       3.98850575, 4.03448276, 4.08045977, 4.12643678, 4.17241379,
       4.2183908 , 4.26436782, 4.31034483, 4.35632184, 4.40229

In [22]:
#random generation  function and also standarization which provide number in between -3 to 3
arr= np.random.rand(5)
arr

array([0.88827153, 0.5455564 , 0.47308547, 0.90935603, 0.47101017])

In [23]:
arr= np.random.randn(5)
arr

array([-0.84298604,  0.49441978, -0.26044994,  1.32146122, -0.10892439])

In [24]:
arr= np.random.randint(5) #this give one random number in between 0-5
arr

2

In [25]:
arr= np.random.randint(10,20,10) #this give random number in between 0-5
arr

array([18, 18, 15, 10, 12, 14, 17, 16, 18, 17], dtype=int32)

In [27]:
#Array Attribute

arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
arr.shape #attributes which which matrix dimension i.e rows and coloum

(3, 3)

In [28]:
arr.size

9

In [29]:
arr.dtype

dtype('int64')

In [30]:
#Array method
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.min()

np.int64(1)

In [32]:
arr.max()


np.int64(9)

In [33]:
arr.sum()

np.int64(45)

In [34]:
#if we want to sum in row and column wise sum then for column we used axis 0(zero) and for row use axis 1(one)
a=np.sum(arr,axis = 0)
a


array([12, 15, 18])

In [36]:
a=arr.mean()
a

np.float64(5.0)

In [37]:
a= arr.std()
a

np.float64(2.581988897471611)

In [39]:
a=arr.argmax()#give index of max value
a

np.int64(8)

In [40]:
a=arr.argmin()#give index of min value
a

np.int64(0)

In [41]:
""" Reshaping and  Resizing"""
arr = np.arange(1,31)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
arr= arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [49]:
#resize : ab jo shape tha wohi rahega ab
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])