In [7]:
 """ Array_Operation """

' Array_Operation '

In [8]:
import numpy as n

In [9]:
""" Arithmatic Operation"""

' Arithmatic Operation'

In [13]:
a1= np.array([1,2,3,4,5]) #number of element in both are same otherwise its gives an error
a2 = np.array([9,8,7,6,10])

In [14]:
a1+a2

array([10, 10, 10, 10, 15])

In [15]:
a1 - a2

array([-8, -6, -4, -2, -5])

In [16]:
a1 * a2

array([ 9, 16, 21, 24, 50])

In [17]:
a1 / a2

array([0.11111111, 0.25      , 0.42857143, 0.66666667, 0.5       ])

In [18]:
a1 // a2

array([0, 0, 0, 0, 0])

In [19]:
 a1 ** a2

array([      1,     256,    2187,    4096, 9765625])

In [21]:
""" BroadCasting
if we want to add any thing in arr with all element which are present inside it then we used this 
"""

' BroadCasting\nif we want to add any thing in arr with all element which are present inside it then we used this \n'

In [22]:
i= [12,23,34,45,56,6,7,78,98,67]
arr = np.array(i)

In [23]:
arr + 20

array([ 32,  43,  54,  65,  76,  26,  27,  98, 118,  87])

In [24]:
arr2 = np.arange(1,51).reshape(10,5)
arr2
                        

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [25]:
arr2 + 99


array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 146, 147, 148, 149]])

In [26]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [27]:
arr2 * 2

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [28]:
""" Deep And Shallow Copy"""

' Deep And Shallow Copy'

In [29]:
#Deep Copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
Slice= a[:5]
Slice = Slice *10
Slice

array([10, 20, 30, 40, 50])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
a
b=a
b[0]=90
b

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
# But you want to do shallow copy not deep copy 
a=np.arange(22,99)

In [42]:
b=a.copy()
b[0]=99
b


array([99, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
a #no change in a , This is called shollow copy

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98])

In [45]:
""" Matrix Multiplication"""

' Matrix Multiplication'

In [46]:
A= np.array([[1,2], [3,4]])
B = np.array([[5,6],[7,8]])

In [47]:
A

array([[1, 2],
       [3, 4]])

In [48]:
B

array([[5, 6],
       [7, 8]])

In [51]:
#multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [52]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
#Transpose in Matrix
A.T

array([[1, 3],
       [2, 4]])

In [55]:
""" Array Manipulation """
""" Stacking Array"""

' Array Manipulation '

In [56]:
A

array([[1, 2],
       [3, 4]])

In [57]:
B

array([[5, 6],
       [7, 8]])

In [58]:
np.vstack((A,B)) #vstack means vertical print element

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((A,B)) #vstack means Horuzental preint element