In [1]:
import numpy as np

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6]

np.int64(17)

In [5]:
#Slicing
arr[1:5]

array([12, 13, 14, 15])

In [6]:
arr[ : 4]

array([11, 12, 13, 14])

In [8]:
arr[ : ]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[3: ]

array([14, 15, 16, 17, 18, 19, 20])

In [11]:
arr_slice= arr[3::2] #here 2 denote number of step jump
arr_slice

array([14, 16, 18, 20])

In [12]:
""" NUMPY INDEXING AND SLICING OF MATRIX"""

arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [13]:
arr[5] #indexing work on row and column 

array([26, 27, 28, 29, 30])

In [15]:
arr[0,0] # means we want to get value at 0r and 0c point

np.int64(1)

In [17]:
arr[0,4]

np.int64(5)

In [18]:
arr[5,4]
#thats means we can also slicing sinle element from matrix

np.int64(30)

In [21]:
slice_2 =arr[0:2,1:3]
slice_2#here we slice out 2 col and 2 row value from matrix

array([[2, 3],
       [7, 8]])

In [23]:
arr[3:6, 3:5] #firstly select row range from where we wnat to print and then select column range from where we want to print it

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])